modLoader="javafml"
loaderVersion="[40,)"
issueTrackerURL="https://modrinth.com/mod/tinkers-thinking"
logoFile="logo.png"
license="MIT"
[[mods]]
modId="tinkers_thinking"
version="0.0.5.3"
displayName="Thinkers' Thinking"
authors="creeping_creeper"
description='''
An addon mod for Tinkers' Construct.
    '''
[[dependencies.tinkers_thinking]]
modId="forge"
mandatory=true
versionRange="[40.1.40,)"
ordering="NONE"
side="BOTH"
[[dependencies.tinkers_thinking]]
modId="tconstruct"
mandatory=true
versionRange="[3.6.3,)"
ordering="NONE"
side="BOTH"