modLoader="javafml"
loaderVersion="[40,)"
issueTrackerURL="https://github.com/CreepingCreeper/Tinkers-Thinking/issues"
logoFile="logo.png"
license="MIT"
[[mods]]
modId="tinkers_thinking"
version="0.1.3.0"
displayName="Thinkers' Thinking"
authors="Creeping Creeper"
description='''
An addon mod for Tinkers' Construct.
    '''
  displayURL="https://www.curseforge.com/minecraft/mc-mods/tinkers-thinking"

[[dependencies.tinkers_thinking]]
modId="minecraft"
mandatory=true
versionRange="[1.19.2]"
ordering="NONE"
side="BOTH"

[[dependencies.tinkers_thinking]]
modId="forge"
mandatory=true
versionRange="[40.1.40,)"
ordering="NONE"
side="BOTH"

[[dependencies.tinkers_thinking]]
modId="tconstruct"
mandatory=true
versionRange="[3.8.1.27,)"
ordering="NONE"
side="BOTH"
